version: '3'

services:

    proj:
        container_name: ${BW_PROJ_NAME}-proj
        image: bazawinner/dev-${BW_PROJ_NAME}-proj:${BW_DEV_PROJ_VERSION}
        entrypoint: ["docker-entrypoint.sh"]
        working_dir: /proj
        restart: always
        tty: true
        environment:
            - PATH=/sh:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - TZ=Europe/Moscow

            - BW_PROJ_NAME
        volumes:
            - ./dev/proj/sh:/sh
            - .:/proj
            - ./registry:/usr/local/cargo/registry
        ports:
            - ${BW_DEV_PROJ_PORT}:8000
